name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install pkg-config opencv libimobiledevice libplist

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Test
        run: make check

      - name: Dist Check
        run: make distcheck
