name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libopencv-dev libimobiledevice-dev

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Test
        run: make check

      - name: Dist Check
        run: make distcheck
