name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        sanitizer: [ address, thread ]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install pkg-config opencv libimobiledevice libplist

      - name: Configure with Sanitizer
        run: |
          ./configure

      - name: Build
        run: |
          if [ "${{ matrix.sanitizer }}" = "address" ]; then
            export CFLAGS="-fsanitize=address -fno-omit-frame-pointer"
            export CXXFLAGS="-fsanitize=address -fno-omit-frame-pointer"
          elif [ "${{ matrix.sanitizer }}" = "thread" ]; then
            export CFLAGS="-fsanitize=thread -fno-omit-frame-pointer"
            export CXXFLAGS="-fsanitize=thread -fno-omit-frame-pointer"
          fi
          make

      - name: Test
        run: make check

      - name: Dist Check
        run: make distcheck
