name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install pkg-config opencv libimobiledevice libplist

      - name: Print Version (verify issue #1)
        run: |
          ls /opt/homebrew/lib | grep imobiledevice || true
          ls /opt/homebrew/lib | grep libplist || true
          ls /opt/homebrew/lib | grep libopencv || true

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Test
        run: make check

      - name: Dist Check
        run: make distcheck
