name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install pkg-config opencv libimobiledevice libplist

      - name: Configure with CMake
        run: |
          ./configure
          mkdir -p build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Test
        run: |
          cd build
          cmake --build . --target check

      - name: Dist Check
        run: |
          cd build
          cmake --build . --target distcheck
